name: Test

on:
  pull_request:
    branches:
      - '*'
    paths:
      - '**/test.py'

jobs:
  test:
    runs-on: ubuntu-latest
    needs: Train
    
  steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
    uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/diagnosis_test:latest .
      
    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/diagnosis_test:latest

    - name: Report success
      run: |
        echo "Build job Completed Successfully"
        exit 0
